namespace Domain.Enums;

/// <summary>
/// Defines the lifecycle status of a visual generation artifact (SceneImage) within a session.
/// </summary>
public enum ArtifactLifecycleStatus
{
    /// <summary>
    /// Candidate artifact generated by an attempt, pending quality evaluation and atomic promotion.
    /// </summary>
    Candidate = 0,

    /// <summary>
    /// Currently active visual representation for the session. Exactly one current artifact allowed per session.
    /// </summary>
    Current = 1,

    /// <summary>
    /// Historical artifact that was once current, now superseded by a newer accepted artifact or regeneration.
    /// </summary>
    Historical = 2,

    /// <summary>
    /// Artifact that failed identity quality guard invariants and has been quarantined.
    /// Invariant: Never promoted to Current and never eligible as a conditioning predecessor.
    /// </summary>
    Quarantined = 3,

    /// <summary>
    /// Artifact marked as deleted or eligible for background cleanup.
    /// </summary>
    Deleted = 4
}
